In [8]:
import random

random.seed(1)
a= random.random()
a= random.uniform(1, 10)
a= random.randint(1,10) # 10 include
a= random.randrange(1, 10) # 10 not include
a - random.normalvariate(0,1)
print(a)




5


In [12]:
mylist = list("acmakckndcn")
a = random.choice(mylist)
print(a)


a


In [6]:
random.shuffle(mylist)
print(mylist)

['a', 'a', 'c', 'c', 'n', 'd', 'c', 'k', 'k', 'n', 'm']


In [15]:
import secrets

a= secrets.randbits(4) # 1111 # 0 to 15
print(a)

1


In [16]:
a = secrets.choice(mylist)
print(a)

NameError: name 'myList' is not defined

In [17]:
import numpy as np

a = np.random.rand(3,3)
print(a)

[[0.26513211 0.90255473 0.86906831]
 [0.3487239  0.63200563 0.579413  ]
 [0.92508623 0.18784683 0.09689244]]


In [19]:
a = np.random.randint(0, 10, (3,3))
print(a)

[[6 0 8]
 [5 6 8]
 [0 0 6]]


In [21]:
arr = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
print(arr)
np.random.shuffle(arr)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [7 8 9]
 [4 5 6]]


In [24]:
np.random.seed(1)
print(np.random.rand(3,3))

[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01 3.96767474e-01]]
